export class ResumeForgeError extends Error {
  constructor(public readonly code: keyof typeof ERROR_CODES, message: string) {
    super(message)
    this.name = 'ResumeForgeError'
  }
}

export const ERROR_CODES = {
  ALIGNMENT_FAILED: 'ALIGNMENT_FAILED',
  GENERATION_FAILED: 'GENERATION_FAILED',
  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  PROFILE_PARSE_FAILED: 'PROFILE_PARSE_FAILED',
  CONFIG_INVALID: 'CONFIG_INVALID',
  CONFIG_WRITE_FAILED: 'CONFIG_WRITE_FAILED',
  API_RATE_LIMITED: 'API_RATE_LIMITED',
  API_UNAVAILABLE: 'API_UNAVAILABLE',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  STORE_CORRUPT: 'STORE_CORRUPT',
  UNKNOWN_CONFIG_KEY: 'UNKNOWN_CONFIG_KEY',
  HISTORY_NOT_FOUND: 'HISTORY_NOT_FOUND',
} as const
